# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 435b24e6233ebefaa12a2e8d060e278d4091218a2490081b3a9004a8bbbf79b2a0fcc8aff5548ce942fc35b7d5cecf505eb4b9b9601eecaebffd226c7df69e1e

test:
  secret_key_base: f7f496fcf64e13a0c94e1830964e8616198e311c8d58de0f53f553feeddcff0649a6d9cf6cfaf69a54ed7c746f5a23f038fef98d6fab992fae9ab16dc8ca1f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
